name: Pylint

on: [pull_request]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Run a code review
      run: |
        q chat --accept-all "You are running inside a GitHub Action. Run a code review on the project and use `gh pr review` to add your feedback."
